name: Push to Production

on:
  push:
    branches: [production]

jobs:
  push-to-production:
    name: Push to Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.AWS_SSH_KEY }}
          known_hosts: ${{ secrets.AWS_KNOWN_HOSTS }}
      - name: Create Context
        run: docker context create --docker host=ssh://ec2-user@ec2-18-232-174-215.compute-1.amazonaws.com api-explorer
      - name: List Local Context
        run: docker context ls
      - name: Get Docker Version
        run: docker -v
      - name: Docker Compose
        run: docker-compose -f docker-compose.prod.yml --context api-explorer up -d
